name: ritual
description: A real pet dating app
publish_to: 'none'
version: 0.4.1+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_spinkit: ^5.2.0
  flutter_launcher_icons: ^0.13.1
  file_picker: ^5.5.0
  restart_app: ^1.2.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  hash: ^1.0.4
  flutter_slidable: ^3.0.0
  shared_preferences: ^2.2.1
  palette_generator: ^0.3.3+3
  flutter_svg: ^2.0.7
  change_app_package_name: ^1.1.0
  duration_picker: ^1.1.1
  flutter_local_notifications: ^16.1.0
  url_launcher: ^6.3.1
  flutter_colorpicker: ^1.0.3
  keep_screen_on: ^3.0.0
  circular_countdown_timer: ^0.2.3
  assets_audio_player: ^3.1.1
  spotlight_ant: ^1.0.5
  awesome_notifications: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/illustrations/
    - assets/audios/

  fonts:
    - family: NotoSans-Light
      fonts:
        - asset: assets/fonts/NotoSans-Light.ttf
    - family: NotoSans-SemiBold
      fonts:
        - asset: assets/fonts/NotoSans-SemiBold.ttf
    - family: Ritual
      fonts:
        - asset: assets/fonts/Ritual.ttf
